In [1]:
import numpy as np

In [3]:
#join two array
arr1=np.array([1,2,3,4])
arr2=np.array([1,2,3,4])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 1 2 3 4]


In [4]:
arr1=np.array([1,2,3,4])
arr2=np.array([[1,2,3,4]])
arr=np.concatenate((arr1,arr2))
print(arr)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

In [7]:
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[6,7,8,9,10]])
print(arr1)
print(arr2)
print()
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)
arrn=np.concatenate((arr1,arr2),axis=1)
print(arrn)

[[1 2 3 4 5]]
[[ 6  7  8  9 10]]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5  6  7  8  9 10]]


In [8]:
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[6,7,8,10]])
print(arr1)
print(arr2)
print()
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2 3 4 5]]
[[ 6  7  8 10]]



ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 5 and the array at index 1 has size 4

In [10]:
arr1=np.array([[1,2,3,4,5]])
arr2=np.array([[6,7,8,9]])
print(arr1)
print(arr2)
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 3 4 5]]
[[6 7 8 9]]
[[1 2 3 4 5 6 7 8 9]]


In [12]:
arr1=np.array([[1,2],[3,4],[5,6]])
arr2=np.array([[6,7],[8,9],[10,11]])
print(arr1)
print(arr2)
print()
arr=np.concatenate((arr1,arr2),axis=0)
print(arr)

[[1 2]
 [3 4]
 [5 6]]
[[ 6  7]
 [ 8  9]
 [10 11]]

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 6  7]
 [ 8  9]
 [10 11]]
